name: PigBash
version: 0.0.0
author: Jan-Luca Klees
main: de.janlucaklees.pigbash.main.PigBash
api-version: 1.16

commands:
  pigbash:
    description: Bash some pigs.
    usage: /pigbash
    permission: de.janlucaklees.pigbash.start
